# Generated by Django 5.0.1 on 2024-01-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_readcsv_rename_book_createcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookId',
            fields=[
                ('book_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateCsv',
        ),
        migrations.AddField(
            model_name='readcsv',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.bookid'),
        ),
    ]
