# Generated by Django 5.0.1 on 2024-01-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookid_delete_createcsv_readcsv_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readcsv',
            name='book',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.bookid'),
        ),
    ]
