@startuml

class CreateDf {

    - generate_random_string()
    - generate_random_date()
    + create_df()
}
class Index画面


class CreateCSV {
    + post()
}
class ReadCSV {
    + post()
}
class DfToDb {
    str: col1
    str: col2
    str: col3
    str: col4

    + insertOrUpdate()
}

CreateDf <-- CreateCSV
Index画面 <|.. CreateCSV
Index画面 <|.. ReadCSV

CreateCSV --> DfToDb
ReadCSV --> DfToDb

@enduml